### ISSUE TITLE
Asset licenses?

### ISSUE THREAD

**Issue by kozross** [a-nikolaev/curseofwar#30]
What license(s) are the assets for this game under?

**Comment by Sicness** [comment]
https://github.com/a-nikolaev/curseofwar/blob/master/LICENSE
Doesn't the file answer on the question?

**Comment by kozross** [comment]
I wasn't sure if that applied to code or assets. Thank you for confirming that it applies to both.

**Comment by Sicness** [comment]
I'm a Debian maintainer of this game and as far as I know, the license is applied for the whole project.

**Comment by a-nikolaev** [comment]
Yeah, the same license for everything. Maybe some Creative Commons license for graphics will work too, but I did not think about this issue too much. Do you want to use the assets for something where GPL is a limitation?

**Comment by kozross** [comment]
@a-nikolaev  Not at all - I'm working on a [small project][1] in the style of the other awesome lists for game development, but wanna ensure that everything on there is both free software *and* free culture. Therefore, it's all good, and I'll include your game as an example for others to follow. Keep doing what you do. :)

[1]: https://notabug.org/koz.ross/awesome-gamedev

**Comment by a-nikolaev** [comment]
Cool, happy to hear that! The list looks great by the way, and the other one, awesome-c, is interesting too. Thanks!

**Comment by Sicness** [comment]
Awesome. Let's close the issue?

**Comment by kozross** [comment]
Sure.
